### ISSUE TITLE
SecretAgent window opens

### ISSUE THREAD

**Issue by sruusk** [claabs/csgostatsgg-scraper#1]
When making requests the SecretAgent browser window and debug tools open and if I close them, new requests will hang.

**Comment by claabs** [comment]
I've only ever run it in headless mode. I'd recommend you also do that:
```js
process.env.SA_SHOW_BROWSER = 'false';
process.env.SA_DISABLE_DEVTOOLS= 'true';
```
([from here](https://github.com/ulixee/secret-agent/blob/62255d9df9b7ae590e226ee84ca852db1ace3ab4/core/lib/GlobalPool.ts#L230-L238))

**Comment by sruusk** [comment]
Thank you. That fixed it. 
I tried running it alongside with my site on heroku and I'm getting this error: 

> ConnectionToClient.HandleRequestError { context: {}, sessionId: [90mundefined[39m, sessionName: [90mundefined[39m } PuppetLaunchError: Failed to launch chrome 88.0.4324.182:
> 2022-02-03T05:36:48.530457+00:00 app[web.1]: 
> 2022-02-03T05:36:48.530458+00:00 app[web.1]: Please re-install the browser engine:
> 2022-02-03T05:36:48.530459+00:00 app[web.1]: -------------------------------------------------
> 2022-02-03T05:36:48.530459+00:00 app[web.1]: -------------- NPM INSTALL ----------------------
> 2022-02-03T05:36:48.530459+00:00 app[web.1]: -------------------------------------------------
> 2022-02-03T05:36:48.530460+00:00 app[web.1]: 
> 2022-02-03T05:36:48.530460+00:00 app[web.1]:  npm install @secret-agent/chrome-88-0
> 2022-02-03T05:36:48.530460+00:00 app[web.1]: 
> 2022-02-03T05:36:48.530460+00:00 app[web.1]: -------------------------------------------------
> 2022-02-03T05:36:48.530461+00:00 app[web.1]: 
> 2022-02-03T05:36:48.530461+00:00 app[web.1]: Error: Failed to launch chrome 88.0.4324.182:
> 2022-02-03T05:36:48.530461+00:00 app[web.1]: 
> 2022-02-03T05:36:48.530461+00:00 app[web.1]: Please re-install the browser engine:
> 2022-02-03T05:36:48.530461+00:00 app[web.1]: -------------------------------------------------
> 2022-02-03T05:36:48.530462+00:00 app[web.1]: -------------- NPM INSTALL ----------------------
> 2022-02-03T05:36:48.530462+00:00 app[web.1]: -------------------------------------------------
> 2022-02-03T05:36:48.530462+00:00 app[web.1]: 
> 2022-02-03T05:36:48.530462+00:00 app[web.1]:  npm install @secret-agent/chrome-88-0
> 2022-02-03T05:36:48.530463+00:00 app[web.1]: 
> 2022-02-03T05:36:48.530463+00:00 app[web.1]: -------------------------------------------------
> 2022-02-03T05:36:48.530463+00:00 app[web.1]: 
> 2022-02-03T05:36:48.530463+00:00 app[web.1]:     at BrowserEngine.verifyLaunchable (/app/node_modules/[4mplugin-utils[24m/lib/BrowserEngine.ts:55:13)
> 2022-02-03T05:36:48.530464+00:00 app[web.1]:     at Puppet.start (/app/node_modules/[4mpuppet[24m/index.ts:64:34)
> 2022-02-03T05:36:48.530464+00:00 app[web.1]:     at Function.getPuppet (/app/node_modules/[4mcore[24m/lib/GlobalPool.ts:120:19)
> 2022-02-03T05:36:48.530464+00:00 app[web.1]:     at Function.createSessionNow (/app/node_modules/[4mcore[24m/lib/GlobalPool.ts:139:33)
> 2022-02-03T05:36:48.530465+00:00 app[web.1]: [90m    at processTicksAndRejections (node:internal/process/task_queues:96:5)[39m
> 2022-02-03T05:36:48.530465+00:00 app[web.1]:     at ConnectionToClient.createSession (/app/node_modules/[4mcore[24m/server/ConnectionToClient.ts:212:21)
> 2022-02-03T05:36:48.530465+00:00 app[web.1]:     at ConnectionToClient.executeCommand (/app/node_modules/[4mcore[24m/server/ConnectionToClient.ts:295:16)
> 2022-02-03T05:36:48.530465+00:00 app[web.1]:     at ConnectionToClient.handleRequest (/app/node_modules/[4mcore[24m/server/ConnectionToClient.ts:70:14) {
> 2022-02-03T05:36:48.530465+00:00 app[web.1]:   isSandboxError: [33mfalse[39m
> 2022-02-03T05:36:48.530465+00:00 app[web.1]: }
> 2022-02-03T05:36:48.547334+00:00 app[web.1]: Error: CoreServer needs further setup to launch the browserEmulator. See server logs.
> 2022-02-03T05:36:48.547337+00:00 app[web.1]:     at ConnectionToClient.serializeError (/app/node_modules/core/server/ConnectionToClient.ts:372:14)
> 2022-02-03T05:36:48.547337+00:00 app[web.1]:     at ConnectionToClient.handleRequest (/app/node_modules/core/server/ConnectionToClient.ts:94:19)
> 2022-02-03T05:36:48.547338+00:00 app[web.1]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> 2022-02-03T05:36:48.547339+00:00 app[web.1]: ------REMOTE CORE---------------------------------
> 2022-02-03T05:36:48.547339+00:00 app[web.1]:     at Function.reviver (/app/node_modules/commons/TypeSerializer.ts:208:26)
> 2022-02-03T05:36:48.547340+00:00 app[web.1]:     at JSON.parse (<anonymous>)
> 2022-02-03T05:36:48.547340+00:00 app[web.1]:     at Function.parse (/app/node_modules/commons/TypeSerializer.ts:24:17)
> 2022-02-03T05:36:48.547340+00:00 app[web.1]:     at WebSocket.<anonymous> (/app/node_modules/client/connections/RemoteConnectionToCore.ts:67:42)
> 2022-02-03T05:36:48.547341+00:00 app[web.1]:     at WebSocket.emit (node:events:390:28)
> 2022-02-03T05:36:48.547358+00:00 app[web.1]:     at Receiver.receiverOnMessage (/app/node_modules/@secret-agent/client/node_modules/ws/lib/websocket.js:1008:20)
> 2022-02-03T05:36:48.547358+00:00 app[web.1]:     at Receiver.emit (node:events:390:28)
> 2022-02-03T05:36:48.547358+00:00 app[web.1]:     at Receiver.dataMessage (/app/node_modules/@secret-agent/client/node_modules/ws/lib/receiver.js:517:14)
> 2022-02-03T05:36:48.547359+00:00 app[web.1]:     at /app/node_modules/@secret-agent/client/node_modules/ws/lib/receiver.js:468:23
> 2022-02-03T05:36:48.547359+00:00 app[web.1]:     at /app/node_modules/@secret-agent/client/node_modules/ws/lib/permessage-deflate.js:308:9
> 2022-02-03T05:36:48.547360+00:00 app[web.1]: ------CONNECTION----------------------------------
> 2022-02-03T05:36:48.547360+00:00 app[web.1]:     at new Resolvable (/app/node_modules/commons/Resolvable.ts:16:18)
> 2022-02-03T05:36:48.547360+00:00 app[web.1]:     at Object.createPromise (/app/node_modules/commons/utils.ts:68:10)
> 2022-02-03T05:36:48.547361+00:00 app[web.1]:     at RemoteConnectionToCore.createPendingResult (/app/node_modules/client/connections/ConnectionToCore.ts:357:31)
> 2022-02-03T05:36:48.547361+00:00 app[web.1]:     at RemoteConnectionToCore.internalSendRequestAndWait (/app/node_modules/client/connections/ConnectionToCore.ts:263:43)
> 2022-02-03T05:36:48.547361+00:00 app[web.1]:     at RemoteConnectionToCore.sendRequest (/app/node_modules/client/connections/ConnectionToCore.ts:164:17)
> 2022-02-03T05:36:48.547362+00:00 app[web.1]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> 2022-02-03T05:36:48.547362+00:00 app[web.1]:     at CoreCommandQueue.sendRequest (/app/node_modules/client/lib/CoreCommandQueue.ts:150:22)
> 2022-02-03T05:36:48.547362+00:00 app[web.1]:     at Object.cb (/app/node_modules/client/lib/CoreCommandQueue.ts:117:16)
> 2022-02-03T05:36:48.547362+00:00 app[web.1]:     at Queue.next (/app/node_modules/commons/Queue.ts:82:19)
> 2022-02-03T05:36:48.547363+00:00 app[web.1]: ------CORE COMMANDS-------------------------------
> 2022-02-03T05:36:48.547363+00:00 app[web.1]:     at Queue.run (/app/node_modules/commons/Queue.ts:35:19)
> 2022-02-03T05:36:48.547363+00:00 app[web.1]:     at CoreCommandQueue.run (/app/node_modules/client/lib/CoreCommandQueue.ts:114:8)
> 2022-02-03T05:36:48.547363+00:00 app[web.1]:     at RemoteConnectionToCore.createSession (/app/node_modules/client/connections/ConnectionToCore.ts:205:51)
> 2022-02-03T05:36:48.547364+00:00 app[web.1]:     at SessionConnection.getCoreSessionOrReject (/app/node_modules/client/lib/Agent.ts:559:36)
> 2022-02-03T05:36:48.547364+00:00 app[web.1]:     at Agent.then (/app/node_modules/client/lib/Agent.ts:443:39)
> 2022-02-03T05:36:48.547365+00:00 app[web.1]:     at /app/node_modules/client/lib/Handler.ts:114:12
> 2022-02-03T05:36:48.547365+00:00 app[web.1]:     at Object.cb (/app/node_modules/client/connections/ConnectionToCore.ts:195:14)
> 2022-02-03T05:36:48.547366+00:00 app[web.1]:     at Queue.next (/app/node_modules/commons/Queue.ts:82:44)
> 2022-02-03T05:36:48.547366+00:00 app[web.1]:     at Queue.run (/app/node_modules/commons/Queue.ts:38:10)
> 2022-02-03T05:36:48.547366+00:00 app[web.1]:     at CoreSessions.waitForAvailable (/app/node_modules/client/lib/CoreSessions.ts:24:23)

Do you have any recommendations or should I just give up on heroku for this?

**Comment by claabs** [comment]
I've never used Heroku personally, but I'll mention that it's important to run `npm install` on the hardware where the program runs. Otherwise it could install incompatible binaries if you're installing on Windows and running on Linux, for example.

My project that uses it has an example of what to perform in a [Dockerfile](https://github.com/claabs/csgo-sus/blob/master/Dockerfile#L21-L30). Also if you're running in Docker, you may need to add `--security-opt seccomp=unconfined` as a parameter, similar to shown [here](https://github.com/ulixee/secret-agent/blob/main/tools/docker/run-core-server.sh).

**Comment by sruusk** [comment]
Heroku runs npm install when deploying. I think I'll have to use something else for the crawler then. Thank you anyways.
